# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-07 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tite', models.TextField(max_length=250)),
                ('body', models.TextField(max_length=250)),
            ],
        ),
    ]
